<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>AfricanStudentsLink</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-COMPATIBLE" content="IE=EmulateIE8" />
<meta http-equiv="imagetoolbar" content="false" />
<meta name="MSSmartTagsPreventParsing" content="true" />
<meta name="Description" content="" />
<meta name="Keywords" content="Template" />
<meta name="author" content="Minwebprom" />
<link rel="icon" href="/favicon.ico" type="image/x-icon" />
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
<link href="css/reset.css" type="text/css" rel="stylesheet" media="all" />
<link href="css/generic.css" type="text/css" rel="stylesheet" media="all" />
<link href="css/print.css" type="text/css" rel="stylesheet" media="print" />
<!--[if lte IE 7]>
<link href="css/ie.css" type="text/css" rel="stylesheet" media="all" />
<![endif]-->
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
</head>
<body>
<!--Main centered block-->
<div class="main clearfix">
<!--Header-->
<div class="head clearfix">
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    
    
    <td class="logo">
   <div class="logo_espace">
    </div>
    </td>
    
    
    <td class="img"></td>
    <td class="menutd">
    <div class="clearfix abovemenu">


    <!--Phone number-->
    <div class="phone">
    <div class="dostavka">
  <!--  <h4>Deposer</h4> 
    <h4>Votre annonce</h4>       -->
     </div>
    </div>

    <div class="cartsearch">
    <!--Search-->
    <form action="" method="get" class="sitesearch"><strong>Moteur de recherche :</strong><input name="" type="text" class="sch" /><input name="" type="image" src="images/loupe_de_recherche.png" alt="Search" /></form>
    <!--Shopcart-->
    <a href="#" title="" class="cart"><strong>Votre Panier</strong><div>0 Produits</div></a>
    </div>
    </div>
    <ul class="clearfix dropdown">
      <li><a href="#" title="">Accueil </a></li>
      <li><a href="#" title="">Les Nouvelles Offres </a>
        <ul class="sub_menu">
                 <li><a href="#">Multimedia</a></li>
                 <li><a href="#">Loisirs</a></li>
                 <li><a href="#">Accessoires Maisons</a></li>
                 <li><a href="#">Immobilier</a></li>
                 <li><a href="#">Accessoires Homme/Femme</a></li>
                 <li><a href="#">Vehicules</a></li>
        </ul>
      </li>
      <li><a href="#" title="">Qui sommes-nous</a>
      <ul class="sub_menu">
               <li><a href="http://myffi.biz/PDF/Testing-Ministry-of-Agrarian-Policy-of-Ukraine.pdf">Incididunt ut labore et dolore magna aliqua</a></li>
            </ul>      
      </li>
      <li class="last"><a href="#" title="">Contactez-nous</a></li>
    </ul>
    </td>
  </tr>
</table>
</div>
<!--Content part-->
<div class="content clearfix">
<!--Left collumn-->
<div class="leftcol" id="set1">
<ul>
  <li class="parent"><span><strong> - Pat Categories - </strong></span></li>
  <li><a href="#" title="Nullus accumsan"><span><strong>Multimedia</strong></span></a></li>
  <li><a href="#" title=""><span><strong>Loisirs</strong></span></a></li>
  <li><a href="#" title=""><span><strong>Accessoires Maisons</strong></span></a></li>
  <li><a href="#" title=""><span><strong>Immobilier</strong></span></a></li>
  <li><a href="#" title=""><span><strong>Accessoires Homme/Femme</strong></span></a></li>
  <li><a href="#" title=""><span><strong>Vehicules</strong></span></a></li>
</ul>
<ul>
  <li class="parent"><span><strong> - Par Pays - </strong></span></li>
  <li><a href="#" title="Nullus accumsan"><span><strong>Mali</strong></span></a></li>
  <li><a href="#" title=""><span><strong>Maroc</strong></span></a></li>
  <li><a href="#" title=""><span><strong>Tunisie</strong></span></a></li>
  <li><a href="#" title=""><span><strong>Algerie</strong></span></a></li>
  <li><a href="#" title=""><span><strong>Ghana</strong></span></a></li>
  <li><a href="#" title=""><span><strong>Senegal</strong></span></a></li>
</ul>
</div>



<!-- La Partie Layout, le reste du site -->
<div class ="rightcol" >
                <?php echo $this->layout()->content; ?>
               
</div>

<div class="footer1 clearfix">
<ul class="clearfix">
       <!--Text block-->
<div class="introtxt clearfix">
  <center>
<h3><strong>Comment Conclure une bonne affaire ?</strong></h3>
<div id="m5Accoridon1" class="m5Accordion">
<div class="m5AccordionPanelTab"><a href="javascript:void(0);" title="Some tooltip" rel="nofollow" class="norm">
<p>L'affaire se passera en 3 simple procedure qui sont :</br>
  - Choisir votre commande</br>
  - Contacter le vendeur</br>
  - Conclure l'affaire
 <span class="more">Afficher</span><span class="more2">Afficher</span></p></a>
</div>
  <div class="m5AccordionPanelContent">
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>
<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?
</p>
<p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.
</p>
</div>
</div>
</div>
</center>
</div>

<!--Footer-->
<div class="footer clearfix">
<ul class="clearfix">
      <li><a title="" href="#">Accueil</a></li>
      <li><a title="" href="#">Les Nouvelles Offres</a></li>
      <li><a title="" href="#">Plan du Site</a></li>
      <li class="last"><a title="" href="#">Contact Us</a></li>
    </ul>
</div>
<div class="counter">© copyright 2012 Propulse par <a href="http://www.thesoftwareweaver.com/" title="AfricanStudentsLink" target="_blank">TheSoftwareweavers</a></div>
</div>
</div>
<script type="text/javascript" language="javascript" src="js/jquery.dropdownPlain.js"></script>
<div class="m5Accordion dontdel" id="m5Accoridon1">
<div class="m5AccordionPanelTab"><a href="javascript:void(0);" rel="nofollow" class="norm">
<img src="images/javascript.png" width="50" height="10" alt="JavaScript" /></a></div>
<div class="m5AccordionPanelContent">
<a href="http://www.theafricanstudentslink.com/"></a></div></div>
<script type="text/javascript" src="js/jquery.m5Accordion.js"></script>
<script type="text/javascript" src="js/scripts.js"></script>
</body>
</html>
