
<!--Right collumn-->
<!--Large image-->
<div class="largeigm">
  <div class="tdrive"> <!-- Partie reserve pour le slider -->
    <h3>Slider</h3>
      <p>Ellum eros capto at capto pecus sudo. Aliquam modo uxor genitus valde quae. Velit fere elit ille autem distineo distineo sino exerciy</p>
      <a href="#" class="enter" title="Click here">Click here</a>
  </div>
</div>
<hr>
<!--What is test-drive
<div class="whatdrive">


</div>

-->







<!--Popular-->
<form action="" method="get" class="popular clearfix">
<h3><strong>Multimedia</strong></h3>
<table border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td class="first"><a href="#" title=""><img src="images/iphone_s5.png" width="107" height="104" alt="Image1" /></a>
    <div class="moreinfo">
    <div class="price">$1299.99</div>
    <strong><a href="#" title="Tescisco">Tescisco</a></strong>
    Quiobruo iusto iusto hendre rerit delenit iusto valde
    <input name="" type="image" value="Add to cart" src="images/addcart.png" alt="Add to cart" />
    </div>
    </td>
    <td>
<a href="#" title=""><img src="images/iphone_s5maroc.jpg" width="107" height="104" alt="Image2" /></a>
    <div class="moreinfo">
    <div class="price">$929.99</div>
    <strong><a href="#" title="Tescisco">Tescisco</a></strong>
    Quiobruo iusto iusto hendre rerit delenit iusto valde
    <input name="" type="image" value="Add to cart" src="images/addcart.png" alt="Add to cart" />
    </div>
    </td>
    <td>
<a href="#" title=""><img src="images/iphone-5.jpg" width="107" height="104" alt="Image3" /></a>
    <div class="moreinfo">
    <div class="price">$599.99</div>
    <strong><a href="#" title="Tescisco">Tescisco</a></strong>
    Quiobruo iusto iusto hendre rerit delenit iusto valde
    <input name="" type="image" value="Add to cart" src="images/addcart.png" alt="Add to cart" />
    </div>
    </td>
  </tr>
</table>

<h3><strong>Immobilier</strong></h3>
<table border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td class="first"><a href="#" title=""><img src="images/image1.jpg" width="107" height="104" alt="Image1" /></a>
    <div class="moreinfo">
    <div class="price">$99.99</div>
    <strong><a href="#" title="Tescisco">Tescisco</a></strong>
    Quiobruo iusto iusto hendre rerit delenit iusto valde
    <input name="" type="image" value="Add to cart" src="images/addcart.png" alt="Add to cart" />
    </div>
    </td>
    <td>
<a href="#" title=""><img src="images/imgage2.jpg" width="107" height="104" alt="Image2" /></a>
    <div class="moreinfo">
    <div class="price">$99.99</div>
    <strong><a href="#" title="Tescisco">Tescisco</a></strong>
    Quiobruo iusto iusto hendre rerit delenit iusto valde
    <input name="" type="image" value="Add to cart" src="images/addcart.png" alt="Add to cart" />
    </div>
    </td>
    <td>
<a href="#" title=""><img src="images/imgage3.jpg" width="107" height="104" alt="Image3" /></a>
    <div class="moreinfo">
    <div class="price">$99.99</div>
    <strong><a href="#" title="Tescisco">Tescisco</a></strong>
    Quiobruo iusto iusto hendre rerit delenit iusto valde
    <input name="" type="image" value="Add to cart" src="images/addcart.png" alt="Add to cart" />
    </div>
    </td>
  </tr>
</table>

<h3><strong>Loisirs</strong></h3>
<table border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td class="first"><a href="#" title=""><img src="images/image1.jpg" width="107" height="104" alt="Image1" /></a>
    <div class="moreinfo">
    <div class="price">$99.99</div>
    <strong><a href="#" title="Tescisco">Tescisco</a></strong>
    Quiobruo iusto iusto hendre rerit delenit iusto valde
    <input name="" type="image" value="Add to cart" src="images/addcart.png" alt="Add to cart" />
    </div>
    </td>
    <td>
<a href="#" title=""><img src="images/imgage2.jpg" width="107" height="104" alt="Image2" /></a>
    <div class="moreinfo">
    <div class="price">$99.99</div>
    <strong><a href="#" title="Tescisco">Tescisco</a></strong>
    Quiobruo iusto iusto hendre rerit delenit iusto valde
    <input name="" type="image" value="Add to cart" src="images/addcart.png" alt="Add to cart" />
    </div>
    </td>
    <td>
<a href="#" title=""><img src="images/imgage3.jpg" width="107" height="104" alt="Image3" /></a>
    <div class="moreinfo">
    <div class="price">$99.99</div>
    <strong><a href="#" title="Tescisco">Tescisco</a></strong>
    Quiobruo iusto iusto hendre rerit delenit iusto valde
    <input name="" type="image" value="Add to cart" src="images/addcart.png" alt="Add to cart" />
    </div>
    </td>
  </tr>
</table>
</form>
</div>
